const data = [
  {
    "id": 1,
    "image": "filepath",
    "name": "Zay Min Maw",
    "phone": "09760614842",
    "gmail": "zayminmaw77@gmail.com",
    "rollcall": 0,
    "major": "Student",
    "address": "Hlaind",
    "payment": 0,
  },
  {
    "id": 2,
    "image": "filepath",
    "name": "Zin Lin Aung",
    "phone": "09760614842",
    "gmail": "zayminmaw77@gmail.com",
    "rollcall": 0,
    "major": "Student",
    "address": "Hlaind",
    "payment": 0,
  },
  {
    "id": 3,
    "image": "filepath",
    "name": "Kaung Sit Thway",
    "phone": "09760614842",
    "gmail": "zayminmaw77@gmail.com",
    "rollcall": 0,
    "major": "Student",
    "address": "Hlaind",
    "payment": 0,
  },
  {
    "id": 4,
    "image": "filepath",
    "name": "Zin Min Nyi Nyi",
    "phone": "09760614842",
    "gmail": "zayminmaw77@gmail.com",
    "rollcall": 0,
    "major": "Student",
    "address": "Hlaind",
    "payment": 0,
  },
  {
    "id": 4,
    "image": "filepath",
    "name": "Zin Min Nyi Nyi",
    "phone": "09760614842",
    "gmail": "zayminmaw77@gmail.com",
    "rollcall": 0,
    "major": "Student",
    "address": "Hlaind",
    "payment": 0,
  },
  {
    "id": 4,
    "image": "filepath",
    "name": "Zin Min Nyi Nyi",
    "phone": "09760614842",
    "gmail": "zayminmaw77@gmail.com",
    "rollcall": 0,
    "major": "Student",
    "address": "Hlaind",
    "payment": 0,
  }
];
